Add status code check

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -49,3 +49,12 @@ jobs:
           FLASK_ENDPOINT='http://127.0.0.1:5000/v1/auth'
           curl -sSL "${FLASK_ENDPOINT}" \
             -H "Authorization: Bearer ${OIDC_TOKEN}"
+          status=$(curl -s -o /dev/null -I -w "%{http_code}" "${URL}")
+          # Return a non-zero exit code if the status code is not 200.
+          if [ "${status}" == "200" ]; then
+              echo "Validation successful!"
+              exit 0
+          else
+              echo "Validation failed!"
+              exit 1
+          fi
